### ISSUE TITLE
Size of LuaTable

### ISSUE THREAD

**Issue by gnavaline** [ouonline/luacpp#1]
Thank you for your code.  I am finding it useful.  I have one question.  I am trying to define a function on the C++ side that will be available on the lua side to compute the AND of a list of numbers.  That requires looping thru every table element as follows.

auto AND = l.CreateFunction([](luacpp::LuaTable t) -> float
	{
		float result = t.GetNumber(1);
		int i = 2;
		// Size() is a function I wrote and added to luacpp
		while (i <= t.Size())
		{
			result = result * t.GetNumber(i);
			i++;
		}
		return result;
	}, "AND");

If you note there is a Size() function here.  I had to add that myself to lua_table.h/lua_table.cpp because I couldn't figure out how to loop thru every element of the table otherwise.  I was previously using your ForEach() function like this along with a global variable called tCount defined outside the function scope.

// AND function.  Same deal as or.
	auto AND = l.CreateFunction([](luacpp::LuaTable t) -> float
	{
		// Function to check for lua table size.  This is really bad coding but I
		// dont know if my lua C++ wrapper can do it any other way.
		tCount = 0;
		auto iterfunc = [](const luacpp::LuaObject& key, const luacpp::LuaObject& value) -> bool
		{
			tCount++;
			return true;
		};
		t.ForEach(iterfunc);

		float result = t.GetNumber(1);
		int i = 2;
		while (i <= tCount)
		{
			result = result * t.GetNumber(i);
			i++;
		}
		return result;
	}, "AND");

I mean I have it working.  But I figured you must have some intended way to do this that I just couldn't figure out.

**Comment by ouonline** [comment]
Hi, I've added `LuaTable::GetSize()` just now. May it help.
